name: Deploy the static file to GitHub Page
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v1
        with:
          ref: src

      - name: build
        run: npm install && npm run build --modern

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          FOLDER: dist
          BRANCH: master
          BASE_BRANCH: src
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
